version: '3.9'

services:
  ui:
    container_name: ui
    build:
      context: .
      args:
        - VITE_API_URL=http://localhost:8888
    ports:
      - 8880:80
    restart: on-failure
    networks:
      - frontend

networks:
  frontend:
    name: "uinet"
