version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL?Variable not set}
    image: plots418890/natours-frontend:dev
    ports:
    - 8880:80
    restart: on-failure
    networks:
    - frontend

networks:
  frontend:
    name: "natoursnet"
