version: '3.9'

services:
  ui:
    container_name: ui
    #    build:
    #  context: .
    #  dockerfile: dev.Dockerfile
#      dockerfile: Dockerfile

    image: plots418890/natours_frontend:dev
    ports:
      - 8880:80
    restart: on-failure
    networks:
      - frontend

networks:
  frontend:
    name: "uinet"
